import os

ENV_NEODB_URL = os.getenv("NEODB_URL")
ENV_NEODB_UNAME = os.getenv("NEODB_UNAME")
ENV_NEODB_PWD = os.getenv("NEODB_PWD")

ENV_OPENAI_DEPLOYMENT_NAME = os.getenv("OPENAI_DEPLOYMENT_NAME")
ENV_OPENAI_BASE_URL = os.getenv("OPENAI_BASE_URL")
ENV_OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
ENV_OPENAI_API_VERSION = os.getenv("OPENAI_API_VERSION")

ENV_S3_FOLDER = os.getenv("S3_ROOT_FOLDER")